# Generated by Django 4.1.2 on 2023-02-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_aksakal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
