# Generated by Django 4.1.2 on 2023-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_chat_is_aksakal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_aksakal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
